### PR TITLE
manifest: sdk-nrfxlib: Pull fix for removing unwanted debug message

### PR DESCRIPTION
**Pull request by VivekUppunda**
This pull brings a simple fix for removing unwanted debug message in sdk-nrfxlib

### CODE REVIEW

**Comment by krish2718** [comment]
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| nrfxlib | https://github.com/nrfconnect/sdk-nrfxlib/commit/a086c1b1fc89c4326926580b84ba3745371a58f9 | https://github.com/nrfconnect/sdk-nrfxlib/pull/1167 | [nrfconnect/sdk-nrfxlib#1167/files](https://github.com/nrfconnect/sdk-nrfxlib/pull/1167/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

**Review by krish2718 — APPROVED** [review]

**Review by sachinthegreen — APPROVED** [review]

**Comment by krish2718** [comment]
@VivekUppunda please sign the CLA

**Comment by VivekUppunda** [comment]
> @VivekUppunda please sign the CLA

@krish2718 - Done. Thanks for pointing it out

**Comment by krish2718** [comment]
can you please rebase and push? @VivekUppunda

**Pull request merged**
