### PR TITLE
manifest: Pull changes to disable DFS channels in scan

### PR DESCRIPTION
**Pull request by ajayparida**
This commit pulls changes for disabling DFS channels in scan.

### CODE REVIEW

**Comment by krish2718** [comment]
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| nrfxlib | https://github.com/nrfconnect/sdk-nrfxlib/commit/a086c1b1fc89c4326926580b84ba3745371a58f9 | https://github.com/nrfconnect/sdk-nrfxlib/pull/1159 | [nrfconnect/sdk-nrfxlib#1159/files](https://github.com/nrfconnect/sdk-nrfxlib/pull/1159/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

**Comment by krish2718** [comment]
if you don't pass this flag, then by default Linux disables DFS channels but Zephyr enables, please fix this.

**Comment by ajayparida** [comment]
> if you don't pass this flag, then by default Linux disables DFS channels but Zephyr enables, please fix this.

Updated the Makefile to handle it. But by default it will be enabled for linux also.

**Review by sachinthegreen — APPROVED** [review]

**Comment by krish2718** [comment]
Manifest will be updated in https://github.com/NordicPlayground/nrf70-linux-driver/pull/45

**Pull request closed without merging**
